const mongoose=require("mongoose");

const UserSchema=new mongoose.Schema({
    name:{
        type:String,
        default:"",
    },
    email:{
        type:String,
        default:"",
        required:[true,"email is mandatory"],
        unique:true,
    },
    password:{
        type:String,
        default:"",
        required:[true,"password is mandatory"]
    },
    phone:{
        type:String,
        default:"",
    },
    role:{
        type:String,
        enum:["user","admin"],
        default:"user",
        require:true,
    },
    code:{
        type:Number,
        default:""
    },
    image:{
        type:String,
        default:""
    },
    isBlocked:{
        type:Boolean,
        default:false
    },
    userAuth:{
        type:String,
        default:"",
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    isForgetPassword:{
        type:Boolean,
        default:false
    },
    isComplete:{
        type:Boolean,
        default:false,
    },
    is_notification:{
        type:Boolean,
        default:false
    },
    device_token:{
        type:String,
        default:"123456789"
    },
    device:{
        type:String,
        default:"Android"
    },
    social_token:{
        type:String,
        default:"987654321"
    },
    social_type:{
        type:String,
        default:"facebook"
    },
    isDelete:{
        type:Boolean,
        default:false
    },
},{
    timestamps:true
});

module.exports=mongoose.model("user",UserSchema);